### ISSUE TITLE
GPU显存

### ISSUE THREAD

**Issue by Miraclerice** [BoyOfChu/LL_Net#1]
你好，正常来说TransMorph模型训练和推理过程不少于10g，论文中的GPU memory为什么才5.236g，这个指标你是怎么计算的

**Comment by BoyOfChu** [comment]
你好，
    显存占用计算方式很多，我也不确定哪种最合适，所以我是用下面torch自带的模块计算的最大的显存占用，没用nvidia-smi的结果：
`print(model_name, "GPU_Memory显存占用为：", torch.cuda.max_memory_allocated(device='cuda:0')/(1024**3), "  GB")`
    理论上，推理应该显存占用远远少于训练，因为不用保存中间结果（显存消耗最大占比）以及梯度信息，但是感觉no_grad和eval没有效果，显存占用和理论值差别比较大。本来是不准备放这个结果的，但是审稿专家的建议计算，所以用了统一的计算方式。
    个人认为最精确的方式应该是将模型权重转为onnx或者tensorrt格式，然后进行推理计算显存，但是这个格式不支持配准网络的STN。。。如果有更精确的显存计算方式，欢迎讨论。
