### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by shy922** [BoyOfChu/LL_Net#2]
论文中图7的可视化是如何做到的呢

**Comment by BoyOfChu** [comment]
我是参照Transmorph的说明，以及Github上其他论文的实现方式。具体原理就是，将输出形变场中心点的值赋1，将其他位置赋0，然后方向传播，计算对输入的梯度，利用颜色可视化后就可以得到了。代码会尽快上传至Infer文件夹，并以ERF开头。
